apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
stringData:
  GITLAB_TOKEN: $GITLAB_TOKEN
  GITHUB_TOKEN: $GITHUB_TOKEN
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  type: git
  url: https://gitlab.com/edgeworks-public
  username: oauth2
  password: $GITLAB_TOKEN
